site_name: Hoch
theme:
  name: material
  lamguage: en
  palette:
    primary: pink
    accent: deep orange
  font:
    text: Rubik
    code: Fira Code
  logo: assets/logo.svg
  favicon: assets/favicon.png
  features:
    - navigation.path
    - navigation.tabs
extra_css:
  - styles/extra.css
nav:
  - Home: index.md
  - Design: design.md
  - Specifications: /specifications
  - Profiles: /profiles
  - Implementions: implementations.md
